"""empty message

Revision ID: c9148f1e5828
Revises: f842864cd003
Create Date: 2023-01-18 12:48:46.323793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9148f1e5828'
down_revision = 'f842864cd003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('users', sa.Column('email', sa.String(), nullable=False))
        op.create_unique_constraint("email", 'users', ['email'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_constraint("email", 'users', type_='unique')
        op.drop_column('users', 'email')
    # ### end Alembic commands ###



